**NUMPY - Learning**
1. What is NumPy and Why Use It?

In [2]:
## Normal python list Vs Numpy Array 

import numpy as np 

python_list1 = [1,2,3,4,5]

Python_list2 = [6,7,8,9,10]

print('--------------------------')
print('OPERATION OVER LISTS')
print('--------------------------')
print(python_list1 + Python_list2)       ### It joins the both lists
## print(python_list1 * Python_list2)
print(python_list1 * 2)
## Numpy Array - FAST for large data 

np_array1 = np.array(python_list1)
np_array2 = np.array(Python_list2)


print('--------------------------')
print('OPERATION OVER Numpy array')
print('--------------------------')

print(np_array1 + np_array2)
print(np_array1 * np_array2)
print(np_array1 * 2)

--------------------------
OPERATION OVER LISTS
--------------------------
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
--------------------------
OPERATION OVER Numpy array
--------------------------
[ 7  9 11 13 15]
[ 6 14 24 36 50]
[ 2  4  6  8 10]


**2. Creating Arrays**

In [7]:
## Creating arrays from lists 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))


## 2D Araar

arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr2d)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Special Arrays**

In [20]:
### Special arrays 


Zeros = np.zeros((3,3))
ones = np.ones((2,2))
empty = np.empty((2,2))
identity = np.eye(2)

print(Zeros)
print('--------')
print(ones)
print('--------')
print(empty)
print('--------')
print(identity)

## Range Arrays 

range_arr = np.arange(0,10,2)               ## It gives list of number with start stop step

print('--------')      
print(range_arr)

linspaase = np.linspace(0,1,5)       ## It will create 5 evenly spaced numbers
print('--------')      
print(linspaase)
random_arr = np.random.randint(1,100, size=(3,3))

print('--------')      
print(random_arr)

random_float = np.random.random((2,3))


print('--------')      
print(random_float)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[1. 0.]
 [0. 1.]]
--------
[0 2 4 6 8]
--------
[0.   0.25 0.5  0.75 1.  ]
--------
[[35 95 74]
 [ 1 23 93]
 [31 51 81]]
--------
[[0.66597171 0.6948936  0.71997257]
 [0.96659594 0.90511112 0.0135925 ]]


**ARRAY PROPERTIES**

In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

### Changing the Data types(Important for memory optimization in Data Engineering)

arr_float = arr.astype(float)
arr_int = arr.astype(np.int32)
print(arr_float)
print(arr_int)


(2, 3)
2
6
int64
[[1. 2. 3.]
 [4. 5. 6.]]
[[1 2 3]
 [4 5 6]]


**ARRAY INDEXING AND SLICING** 



In [20]:
arr = np.array([10, 20, 30,40,50])

print(arr[0])
print(arr[-1])
print(arr[0:4])


## 2D ARRAY

arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr2d[0][1])
print(arr2d[0:2, 0:2])
print(arr2d[0,:])
print(arr2d[:,1])


## Boolen Indexing(Super Useful in Data Engineering)

sales = np.array([100,200,300,400,500, 90, 46])

##Find all sales greater than 150

high_sales = sales[sales > 150]
print(high_sales)

## Find indicies of all sales is greater than 150 

indicies = np.where(sales > 150 )
print(indicies)




10
50
[10 20 30 40]
2
[[1 2]
 [4 5]]
[1 2 3]
[2 5 8]
[200 300 400 500]
(array([1, 2, 3, 4]),)


**Array Operations**

In [21]:
arr = np.array([1,2,3,4,5])

print(arr * 10)
print(arr+10)
print(arr **2)
print(arr/2)

[10 20 30 40 50]
[11 12 13 14 15]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]


In [24]:
## Array Vs Array

arr2 = np.array([10,20,30,40,50])

print(arr + arr2)
print(arr * arr2)

data = np.array([15,25,35,45,55,66])

print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.min(data))
print(np.max(data))
print(np.cumsum(data))

[11 22 33 44 55]
[ 10  40  90 160 250]
241
40.166666666666664
40.0
17.324516988617283
15
66
[ 15  40  75 120 175 241]


In [37]:
arr = np.arange(1,13)
print(arr.size)
print(arr)

matrix= arr.reshape(3,4)
print(matrix)
matrix2 = arr.reshape(2,2,3)
print(matrix2)

flat=matrix2.flatten()
print(flat)

12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
