**NUMPY - Learning**
1. What is NumPy and Why Use It?

In [4]:
## Normal python list Vs Numpy Array 

import numpy as np 

python_list1 = [1,2,3,4,5]

Python_list2 = [6,7,8,9,10]

print('--------------------------')
print('OPERATION OVER LISTS')
print('--------------------------')
print(python_list1 + Python_list2)       ### It joins the both lists
## print(python_list1 * Python_list2)
print(python_list1 * 2)
## Numpy Array - FAST for large data 

np_array1 = np.array(python_list1)
np_array2 = np.array(Python_list2)


print('--------------------------')
print('OPERATION OVER Numpy array')
print('--------------------------')

print(np_array1 + np_array2)
print(np_array1 * np_array2)
print(np_array1 * 2)

--------------------------
OPERATION OVER LISTS
--------------------------
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
--------------------------
OPERATION OVER Numpy array
--------------------------
[ 7  9 11 13 15]
[ 6 14 24 36 50]
[ 2  4  6  8 10]


**2. Creating Arrays**

In [7]:
## Creating arrays from lists 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))


## 2D Araar

arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr2d)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Special Arrays**

In [20]:
### Special arrays 


Zeros = np.zeros((3,3))
ones = np.ones((2,2))
empty = np.empty((2,2))
identity = np.eye(2)

print(Zeros)
print('--------')
print(ones)
print('--------')
print(empty)
print('--------')
print(identity)

## Range Arrays 

range_arr = np.arange(0,10,2)               ## It gives list of number with start stop step

print('--------')      
print(range_arr)

linspaase = np.linspace(0,1,5)       ## It will create 5 evenly spaced numbers
print('--------')      
print(linspaase)
random_arr = np.random.randint(1,100, size=(3,3))

print('--------')      
print(random_arr)

random_float = np.random.random((2,3))


print('--------')      
print(random_float)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[1. 0.]
 [0. 1.]]
--------
[0 2 4 6 8]
--------
[0.   0.25 0.5  0.75 1.  ]
--------
[[35 95 74]
 [ 1 23 93]
 [31 51 81]]
--------
[[0.66597171 0.6948936  0.71997257]
 [0.96659594 0.90511112 0.0135925 ]]
